try {
    functionThatMightThrow();
  } catch (error) {
    console.log(error);
  }